### ISSUE TITLE
Having a different root problem

### ISSUE THREAD

**Issue by lukavia** [lovasoa/SQLpage#141]
### Introduction

I've been building from git for a few weeks now. After the latest pull and build my app couldn't find the pages anymore.
I start the binary in dir **web** where I have 2 sub dirs: **web/pages** and **web/sqlpage/** 
My config is at web/sqlpage/sqlpage.json and it does get read, because if I open the web address I see a page that reads: 
current working directory: [...]/web/pages
You can customize your server's [configuration](https://github.com/lovasoa/SQLpage/blob/main/configuration.md) by creating a file in [...]/web/pages/sqlpage/sqlpage.json

### To Reproduce

Move the .sql files in sub dir and point web_root to it sqlpage/sqlpage.json

### Version information

 - OS: Ubuntu
 - Database sqlite
 - SQLPage Version git checkout 8216313fc98

**Comment by lovasoa** [comment]
Hello ! I just pushed a commit to revert the problematic change.

It's nice to get such fast feedback, but I'm wondering what your use of sqlpage may be ? Is it the first time you encounter an issue, running directly from the main branch ?

**Comment by lukavia** [comment]
I confirm after the revert it works again. 
Yes, this is the first time I encounter an issue running from the main branch. 

If you are asking why I'm building myself and using it that way... I wanted to test the column alignment before it was released, so I've build it :) ... and since I have the setup of building myself I decided to run it like this so I can test new cool features when you add them. Or even contribute if I have a chance at some point. 

May be I should have mentioned that I've just switch to the official release so there was no hurry in fixing this. Sorry. 

If you are asking something else, please let me know and I'll be glad to answer. 

I think this is a great project and would love to help anyway I can.

**Comment by lovasoa** [comment]
I'm asking because I'm giving [a talk about SQLPage](https://sql.ophir.dev/blog.sql?post=Come%20see%20me%20build%20twitter%20live%20on%20stage%20in%20Prague) next month, and I have a section in my presentation about examples of what people have built with SQLPage, how they are using it, and why. I have already collected a few interesting testimonies, some of them quite unusual, but I'm always looking for more :) So if you can write a few words about what you are using SQLPage for, or even better, if we can have a short call together (`contact@ophir.dev`), I would be very happy !
